name: Go

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - main.go
      - .github/workflows/go.yml
  pull_request:
    branches: ["main"]
    paths:
      - main.go
      - .github/workflows/go.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build
        run: go build -v ./.

      - name: Cache
        uses: actions/cache@v3.3.2
        with:
          path: go-grep-cache
          key: ${{ runner.os }}-go-grep-cache
